include:
- access_management/*
kind: ArchiveUploadSpec
name: access-management-Kz0I

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: rabbitmq-producer-8e793674-e237-42c6-8419-fad1521db8e9
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://access-management-Kz0I
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-02T03:38:09Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: rabbitmq-producer
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.main
    packageref:
      name: rabbitmq-producer-8e793674-e237-42c6-8419-fad1521db8e9
      namespace: ""
  requestsPerPod: 1
  resources: {}
