include:
- notification_management_pkg/*
kind: ArchiveUploadSpec
name: notification-management-pkg-luOk

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-consumer-598d3683-5f42-41df-b2f0-4dd5b3855653
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://notification-management-pkg-luOk
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-05T09:04:12Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: notification-consumer
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: notification_management.main.message_queue_entrypoint
    packageref:
      name: notification-consumer-598d3683-5f42-41df-b2f0-4dd5b3855653
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
include:
- notification_management_pkg/*
kind: ArchiveUploadSpec
name: notification-management-pkg-s5xQ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-consumer-317a4d9f-ded7-4064-9cf4-01c4f607520f
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://notification-management-pkg-s5xQ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-05T09:05:16Z"
