include:
- access_management_pkg/*
kind: ArchiveUploadSpec
name: access-management-pkg-EsPL

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: accessmanagement-consumer-48f9a9a5-1dae-4934-a3e1-16231e503b9b
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://access-management-pkg-EsPL
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-05T07:14:48Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: accessmanagement-consumer
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: access_management.main.consumer
    packageref:
      name: accessmanagement-consumer-48f9a9a5-1dae-4934-a3e1-16231e503b9b
      namespace: ""
  requestsPerPod: 1
  resources: {}
