apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: rabbitmq-producer-route
spec:
  createingress: false
  functionref:
    functionweights: null
    name: rabbitmq-producer
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /producer
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /producer
